### ISSUE TITLE
Wont work agter upgrading to Python3.9

### ISSUE THREAD

**Issue by Ram-WD** [ben981/scriptifier#5]
the fallowing script : 

```
> from datetime import datetime
> import tensorflow as tf
> import  pickle
> import os
> 
> def simulate(guidelines_dict):
>     from Mudera_Objects_v1.Learners.MIMO_MetaLearner.MIMO_MetaLearner import MIMO_MetaLearner
>     tf.config.run_functions_eagerly(True)
>     a = MIMO_MetaLearner(guidelines_dict=guidelines_dict)
>     return True
> 
> 
> 
> if __name__ == '__main__':
>     from scriptifier import scriptifier
>     scriptifier_simulator = scriptifier.run_as_script(simulate)
>     from Mudera_Objects_v1.MUDRA_constants import *
>     from Mudera_Objects_v1.Learners.MIMO_MetaLearner.base_config import guidelines_dict
>     guidelines_dict["epochs"] = 1
>     main_dir = LOGS_DIRECTORY + f"/compering_different_optimizers_partitioning"  # + datetime.now().strftime("%Y%m%d-%H%M%S")
>     optimizers_partitioning_list = [
>         {
>             "shared_vars": "Adam",
>             "classifier" : "Adamax",
>             "segmentor"  : "Adamax", },
>         {
>             "shared_vars": "Adamax",
>             "classifier" : "Adam",
>             "segmentor"  : "Adam", },
>         {
>             "shared_vars": "Adamax",
>             "classifier" : "AdamBelief",
>             "segmentor"  : "AdamBelief", },
>         {
>             "shared_vars": "AdamBelief",
>             "classifier" : "Adamax",
>             "segmentor"  : "Adamax", },
>     ]
>     for optimizers_partitioning in optimizers_partitioning_list:
>         guidelines_dict["optimizers_names_dict"]= optimizers_partitioning
>         sim_name =f"sv-{optimizers_partitioning['shared_vars']}_c-{optimizers_partitioning['classifier']}_s-{optimizers_partitioning['segmentor']}"
>         guidelines_dict["output_dir"] = f"{main_dir}/{sim_name}"
>         scriptifier_simulator(guidelines_dict)

```

**raise the next error:** 

> sh: 1: python: not found
> Traceback (most recent call last):
>   File "/usr/lib/python3.9/code.py", line 90, in runcode
>     exec(code, self.locals)
>   File "<input>", line 1, in <module>
>   File "/snap/pycharm-professional/271/plugins/python/helpers/pydev/_pydev_bundle/pydev_umd.py", line 198, in runfile
>     pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
>   File "/snap/pycharm-professional/271/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
>     exec(compile(contents+"\n", file, 'exec'), glob, loc)
>   File "/home/wld-algo/PycharmProjects/DataScienceRam/Ram_playground/simulation_epic0.py", line 43, in <module>
>     scriptifier_simulator(guidelines_dict)
>   File "/home/wld-algo/.local/lib/python3.9/site-packages/scriptifier/scriptifier.py", line 146, in wrapper
>     returns = returns_loader(current_call_directory, tf_exclude_gpu)
>   File "/home/wld-algo/.local/lib/python3.9/site-packages/scriptifier/scriptifier.py", line 89, in returns_loader
>     returns = pickle.load(open(os.path.join(current_call_directory, "RETURNS.pickle"), 'rb'))
> FileNotFoundError: [Errno 2] No such file or directory: '/home/wld-algo/.local/lib/python3.9/site-packages/scriptifier/io/1/RETURNS.pickle'

**Comment by ben981** [comment]
The package passes all tests on Python 3.9. I assume there is an issue in the function.
